// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token     string `json:"token"`
	ExpiresIn int64  `json:"expiresIn"`
}

type ProfileRequest struct{}

type ProfileResponse struct {
	Username string `json:"username"`
}

type DashboardRequest struct{}

type DashboardResponse struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}
