apiVersion: v1
kind: Service
metadata:
  name: p2p-backend
  namespace: p2p-exchange
spec:
  selector:
    app: p2p-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: p2p-exchange
