Name: p2p-api
Mode: dev
Host: 0.0.0.0
Port: 8888

Database:
  DSN: "postgresql://neondb_owner:npg_MnU4eHLIsBS8@ep-holy-thunder-axqogoxt-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

Redis:
  Addr: "stem-destined-cheese-29981.db.redis.io:16698"
  Password: "mvGFzf9sBAlCdGl1fVBEnLWPz7yJbmTh"
  PoolSize: 10

WebSocket:
  Enabled: true
  Host: 0.0.0.0
  Port: 8889